import { Agent } from '@/types';

export const AGENTS: Agent[] = [
  {
    id: 'claude',
    name: 'Claude',
    provider: 'Anthropic',
    description: 'Elite reasoning, coding & analysis',
    color: '#D97706',
    icon: '🟠',
    apiKeyName: 'ANTHROPIC_API_KEY',
    defaultModel: 'claude-3-7-sonnet-20250219',
    availableModels: [
      'claude-3-7-sonnet-20250219',
      'claude-3-5-sonnet-20241022',
      'claude-3-5-haiku-20241022',
      'claude-3-opus-20240229',
    ],
    defaultBaseUrl: 'https://api.anthropic.com/v1',
  },
  {
    id: 'gpt4',
    name: 'GPT & OpenAI',
    provider: 'OpenAI',
    description: 'Versatile logic, tool use & reasoning',
    color: '#10A37F',
    icon: '🟢',
    apiKeyName: 'OPENAI_API_KEY',
    defaultModel: 'gpt-4o',
    availableModels: [
      'gpt-4o',
      'gpt-4o-mini',
      'o1',
      'o1-mini',
      'o3-mini',
      'gpt-4-turbo',
      'chatgpt-4o-latest',
    ],
    defaultBaseUrl: 'https://api.openai.com/v1',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    provider: 'Google',
    description: 'Ultra-fast multimodal, code & large context',
    color: '#4285F4',
    icon: '🔵',
    apiKeyName: 'GOOGLE_API_KEY',
    defaultModel: 'gemini-2.5-flash',
    availableModels: [
      'gemini-2.5-flash',
      'gemini-2.5-pro',
      'gemini-2.0-flash',
      'gemini-1.5-pro',
      'gemini-1.5-flash',
    ],
    defaultBaseUrl: 'https://generativelanguage.googleapis.com',
  },
  {
    id: 'grok',
    name: 'Grok',
    provider: 'xAI',
    description: 'Bold, real-time reasoning & code intelligence',
    color: '#EF4444',
    icon: '🔴',
    apiKeyName: 'XAI_API_KEY',
    defaultModel: 'grok-3',
    availableModels: [
      'grok-3',
      'grok-2',
      'grok-2-vision',
      'grok-beta',
    ],
    defaultBaseUrl: 'https://api.x.ai/v1',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    provider: 'DeepSeek',
    description: 'Deep mathematical & algorithmic reasoning',
    color: '#8B5CF6',
    icon: '🟣',
    apiKeyName: 'DEEPSEEK_API_KEY',
    defaultModel: 'deepseek-chat',
    availableModels: [
      'deepseek-chat',
      'deepseek-reasoner',
    ],
    defaultBaseUrl: 'https://api.deepseek.com/v1',
  },
  {
    id: 'hermes',
    name: 'Hermes',
    provider: 'Nous Research',
    description: 'Autonomous reasoning, self-learning & function calling',
    color: '#F97316',
    icon: '🪽',
    apiKeyName: 'HERMES_API_KEY',
    defaultModel: 'nousresearch/hermes-3-llama-3.1-405b',
    availableModels: [
      'nousresearch/hermes-3-llama-3.1-405b',
      'nousresearch/hermes-3-llama-3.1-70b',
      'nousresearch/hermes-2-pro-llama-3-8b',
      'nousresearch/hermes-2-theta-llama-3-8b',
      'hermes-3-llama-3.1-8b',
    ],
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
  },
];

export function getAgent(id: string): Agent | undefined {
  return AGENTS.find((a) => a.id === id);
}
